apiVersion: v1
  kind: Ingress
  metadata:
    name:httpingress 
    namespace: foo
  spec:
    ingressClassName:httpserver
    rules:
      - host: www.httpserver.com
        http:
          paths:
            - backend:
                service:
                  name: httpserverService
                  port:
                    number: 80
                  path: /
    tls:
      - hosts:
        - www.httpserver.com
        secretName: httpserver-tls
---
apiVersion: v1
  kind: Secret
  metadata:
    name: httpserver-tls 
    namespace: foo
  data:
    tls.crt: ***
    tls.key: *** 
  type: kubernetes.io/tls